$content = Get-Content "README.md" -Raw -Encoding UTF8

# Remove various emojis systematically
$content = $content -replace "✅", ""
$content = $content -replace "🔲", ""
$content = $content -replace "🔄", ""
$content = $content -replace "🎯", ""
$content = $content -replace "📄", ""
$content = $content -replace "📝", ""
$content = $content -replace "🔗", ""
$content = $content -replace "📊", ""
$content = $content -replace "📋", ""
$content = $content -replace "🧪", ""
$content = $content -replace "⚙️", ""
$content = $content -replace "🚀", ""
$content = $content -replace "📈", ""
$content = $content -replace "🔒", ""
$content = $content -replace "👥", ""
$content = $content -replace "📞", ""
$content = $content -replace "🛒", ""
$content = $content -replace "🏗️", ""
$content = $content -replace "🌱", ""
$content = $content -replace "📖", ""
$content = $content -replace "🗺️", ""
$content = $content -replace "🔮", ""
$content = $content -replace "📸", ""
$content = $content -replace "🏆", ""
$content = $content -replace "⚠️", ""
$content = $content -replace "📚", ""
$content = $content -replace "♻️", ""
$content = $content -replace "🌍", ""
$content = $content -replace "🔧", ""
$content = $content -replace "🐳", ""
$content = $content -replace "📜", ""
$content = $content -replace "🗃️", ""
$content = $content -replace "🌐", ""
$content = $content -replace "📦", ""
$content = $content -replace "📱", ""
$content = $content -replace "🎉", ""
$content = $content -replace "📅", ""
$content = $content -replace "👨‍💻", ""
$content = $content -replace "⚡", ""
$content = $content -replace "📌", ""
$content = $content -replace "🟡", ""
$content = $content -replace "🟢", ""
$content = $content -replace "🔴", ""
$content = $content -replace "💰", ""
$content = $content -replace "🛡️", ""
$content = $content -replace "🎨", ""

Set-Content "README.md" -Value $content -Encoding UTF8
Write-Host "Emojis removed successfully!"